function imgName = selectImgName(substrate,caseExp)
switch substrate
    case 'Unduloid'
        switch caseExp
            case 'D8ConvexDiff'
                imgName = {'example_data/20191204_D8ConvexDiffBS2Unduloid_actin',...
                    'example_data/20191212_D8ConvexDiffBS4Unduloid_actin',...
                    'example_data/20200116_D8ConvexDiffS2Unduloid_actin',...
                    'example_data/20200121_D8ConvexDiffS4Unduloid_actin'};
        end
    case 'Cylinder'
        switch caseExp
            case 'D8ConvexDiff'
                imgName = {'example_data/20191204_D8ConvexDiffBS2Cylinder_actin',...
                    'example_data/20191212_D8ConvexDiffS4BCylinder_actin',...
                    'example_data/20200121_D8ConvexDiffS4Cylinder_actin'};
        end
    case 'Spheres'
        switch caseExp
            case 'D8ConvexDiff'
                imgName = {'example_data/20191204_D8ConvexDiffBS2Spheres_actin',...
                    'example_data/20191212_D8ConvexDiffS4BSpheres_actin',...
                    'example_data/20200116_D8ConvexDiffS2Spheres_actin',...
                    'example_data/20200121_D8ConvexDiffS4Spheres_actin'};

        end
    case 'Wavy'
        switch caseExp
            case 'D8ConvexDiff'
                imgName = {'example_data/20191204_D8ConvexDiffBS2Wavy_actin',...
                    'example_data/20191212_D8ConvexDiffS4BWavy_actin',...
                    'example_data/20200116_D8ConvexDiffS2Wavy_actin',...
                    'example_data/20200121_D8ConvexDiffS4Wavy_actin'};
           
        end
    case 'Pseudospheres'
        switch caseExp
            case 'D8ConvexDiff'
                imgName = {'example_data/20191204_D8ConvexDiffBS2Pseudospheres_actin',...
                    'example_data/20191212_D8ConvexDiffS4BPseudospheres_actin',...
                    'example_data/20200116_D8ConvexDiffS2Pseudospheres_actin',...
                    'example_data/20200121_D8ConvexDiffS4Pseudospheres_actin'};
            
        end
    case 'Catenoids'
        switch caseExp
            case 'D8ConvexDiff'
                imgName = {'example_data/20191204_D8ConvexDiffBS2Catenoids_actin',...
                    'example_data/20191212_D8ConvexDiffS4BCatenoids_actin',...
                    'example_data/20200116_D8ConvexDiffS2Catenoid_actin',...
                    'example_data/20200121_D8convexDiffS4Catenoid_actin'};
            
        end
end